apiVersion: v1
kind: Secret
metadata:
  name: url-shortener-secret
  labels:
    app: url-shortener
type: Opaque
data:
  # Base64 encoded value for: /app/data/url-shortener.db
  database-url: L2FwcC9kYXRhL3VybC1zaG9ydGVuZXIuZGI=
